server:
  port: 8888

spring:
  application:
    name: gateway
  config:
    import: 'configserver:http://${CONFIG_SERVER_HOST:localhost:8083}'

#spring:
#  threads:
#    virtual:
#      enabled: true
#  cloud.gateway.mvc:
#    routesMap:
#      monoMartCatalogRoutes:
#        uri: 'http://${INVENTORY_HOST:localhost:8081}'
#        predicates:
#          - Path=/api/catalogs/**
#      monoMartProductRoutes:
#        uri: 'http://${INVENTORY_HOST:localhost:8081}'
#        predicates:
#          - Path=/api/products/**
#      monoMartRoutes:
#        uri: 'http://${MONOMART_HOST:localhost:8080}'
#        predicates:
#          - Path=/**

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: 'http://${ZIPKIN_HOST:localhost:9411}/api/v2/spans'
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'